# Generated by Django 5.1.6 on 2025-03-03 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=20)),
                ('sector', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('image_url', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('tab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='portfolio.tab')),
            ],
        ),
    ]
